api:
  build: ./
  ports:
    - 3000:3000
  volumes:
    - ./:/go/src/github.com/superlinkx/project-healthpack
  links:
    - database
  environment:
    - DB_NAME=project-healthpack
  
database:
  image: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: healthpack