api:
  build: ./api
  ports:
    - 3000:3000
  volumes:
    - ./api:/go/src/github.com/superlinkx/project-healthpack/api
  links:
    - database
  environment:
    - DB_NAME=project-healthpack
  
database:
  image: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: healthpack